### ISSUE TITLE
Chaurus Pheromones potion doesn't work on Chaurus Studs near Abandoned Shack

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SkLLmods#1331]
Potion's MGEF condition checks for vanilla Chaurus Faction, which Chaurus Stud is not a member of.

**Comment by SkyrimLL** [comment]
Chaurus studs are part of a custom faction which is allied with the Chaurus faction and includes several members.
The issue is caused by the way the magic effect is set up. I was expecting it to stay active for a while but the duration is not taken into account, possibly because it is a fire and forget type of spell. 
Anyway.. I fixed it internally and the pheromone spell now works in testing.
