### ISSUE TITLE
CTD in fjotra's prison

### ISSUE THREAD

**Issue by tarkan9801** [SkyrimLL/SkLLmods#750]
Hi i got CTD when trying to enter last part of broken tower. also got CTD on blind cliff bastion

**Comment by SkyrimLL** [comment]
Check the discussions in the main forum thread: https://www.loverslab.com/topic/21873-the-sisterhood-of-dibella-april-2019/

This is due to issue with textures conversions for the SSE edition of the game. 
Other people than me are working on that issue. I will release an update whenever they provide me with the patched files.

**Comment by SkyrimLL** [comment]
See a potential solution here:
https://www.loverslab.com/topic/21873-the-sisterhood-of-dibella-april-2019/page/131/?tab=comments#comment-2679585
