### ISSUE TITLE
Hormone levels are initially set and never changed after that

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SkLLmods#828]
Hormone levels are set to an initial value in the SLH_fctHormonesLevels function setHormonesLevels, but this is never called again to update those values, nor are they separately updated on their own. **The function setHormonesLevels looks to be meant to be called often, but it's never called again beyond the initial setup.**

Because of this, changing the hormone mod values in the MCM does not update their associated hormone values. Also, hormone values do not change on the day to day or based on events. 

As a result, hormone levels never change from their initial preset value. The most glaring example of this is that the Bimbo Hormone is always 0. Since the values are set when the mod is first installed and never after that, the curse is prevented from becoming permanent which causes it to repeat the last day 15+ stage.

**Comment by SkyrimLL** [comment]
The issue with Hormone levels not changing was probably fixed since this issue was reported.

To clarify a little:

setHormonesLevels()  is meant to be used for a first time initialization only. I added a comment in the function about that.

To modify hormone levels, I use the modHormoneLevel() and cooldownHormoneLevel() functions, which use the 'mod' values internally, so these modifiers are always used according to the values set in the menu.
