### ISSUE TITLE
SLH_QST_BimboAlias Bimbo progressive transformation issues

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/SkLLmods#829]
Due to how the math in bimboDailyProgressiveTransformation is written:
```
int transformationDays = StorageUtil.GetIntValue(bimbo, "_SLH_bimboTransformGameDays")
int transformCycle = transformationDays/5
int transformationLevel = transformationDays - (transformCycle * 5)
```
Transformation levels 1, 2, 3, 4 progressively occur twice: day 6, 7, 8, 9 then again on day 11, 12, 13, 14.

Additionally, transformationLevel 5 will never occur. The equation for transformationLevel only ever goes up to 4, starting over at 0 after that.
```
Day 1-5 = transformationLevel 0
Day 6 = transformationLevel 1
Day 7 = transformationLevel 2
Day 8 = transformationLevel 3
Day 9 = transformationLevel 4
Day 10 = transformationLevel 0
Day 11 = transformationLevel 1
Repeat.
```

Since I'm not good at math, I'm unable to think of a formula that would best progressively catch only transformation days 6-10 without also adding a several extra checks. Which doesn't seem like a good alternative.

**Comment by SkyrimLL** [comment]
Thanks for pointing out the math issue.
I updated the code to clarify what each variable was supposed to be. 

Days - should be the number of days since the bimbo curse started
Cycle - should be the number of refresh cycles for the curse effects in case they are removed by other means (reset every 5 days). 1 cycle = 5 days
Level - should be the level of the transformation in the curse - should progress from 1 to 5 during the first cycle and remain at 5 after that.

**Comment by z45949355** [comment]
I want this function can make make up change every day，and  in the newest version ,bimbo's hair color can't change
